export const GET_ERROR = 'GET_ERROR'

export const GET_USER = 'GET_USER'
export const GET_USER_SESSION = 'GET_USER_SESSION'
export const GET_ALL_UNIVERSITY = 'GET_ALL_UNIVERSITY'
export const GET_ALL_GENDER = 'GET_ALL_GENDER'
export const GET_ALL_NATIONALITY = 'GET_ALL_NATIONALITY'
export const GET_ALL_QUALIFICATION = 'GET_ALL_QUALIFICATION'
export const GET_ALL_ADMISSION = 'GET_ALL_ADMISSION'
export const GET_ALL_ACADEMIC = 'GET_ALL_ACADEMIC'

export const CREATE_EMAIL_CONFIRMATION = 'CREATE_EMAIL_CONFIRMATION'
export const CREATE_ACTIVATE_EMAIL = 'CREATE_ACTIVATE_EMAIL'

export const UPDATE_USER = 'UPDATE_USER'
