export const GET_ERROR = 'GET_ERROR'

export const GET_USER = 'GET_USER'
export const GET_USER_SESSION = 'GET_USER_SESSION'
export const GET_ALL_UNIVERSITY = 'GET_ALL_UNIVERSITY'

export const CREATE_EMAIL_CONFIRMATION = 'CREATE_EMAIL_CONFIRMATION'
export const CREATE_ACTIVATE_EMAIL = 'CREATE_ACTIVATE_EMAIL'
